"use client";

import { useEffect, useState, useCallback } from "react";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { format } from "date-fns";

type OfferStatus = "DRAFT" | "SENT" | "CLAIMED" | "EXPIRED";

interface Offer {
  id: string;
  slotId: string;
  ruleId: string;
  businessId: string;
  discountPercent: number;
  discountedPriceCents: number;
  status: OfferStatus;
  disabledByUser: boolean;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
  slot: {
    id: string;
    serviceType: string;
    startTime: string;
    endTime: string;
    basePriceCents: number;
  };
  rule: {
    id: string;
    name: string;
  };
}

type FilterTab = "ALL" | OfferStatus;

const STATUS_BADGE_MAP: Record<
  OfferStatus,
  { label: string; variant: "default" | "info" | "success" | "danger" }
> = {
  DRAFT: { label: "Draft", variant: "default" },
  SENT: { label: "Sent", variant: "info" },
  CLAIMED: { label: "Claimed", variant: "success" },
  EXPIRED: { label: "Expired", variant: "danger" },
};

const FILTER_TABS: { key: FilterTab; label: string }[] = [
  { key: "ALL", label: "All" },
  { key: "DRAFT", label: "Draft" },
  { key: "SENT", label: "Sent" },
  { key: "CLAIMED", label: "Claimed" },
  { key: "EXPIRED", label: "Expired" },
];

function formatPrice(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

export default function OffersPage() {
  const [offers, setOffers] = useState<Offer[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<FilterTab>("ALL");
  const [togglingId, setTogglingId] = useState<string | null>(null);

  const fetchOffers = useCallback(async () => {
    try {
      const res = await fetch("/api/offers");
      if (!res.ok) {
        const data = await res.json();
        toast.error(data.error || "Failed to load offers");
        return;
      }
      const data = await res.json();
      setOffers(data);
    } catch {
      toast.error("Something went wrong loading offers");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchOffers();
  }, [fetchOffers]);

  async function toggleDisabled(offer: Offer) {
    setTogglingId(offer.id);
    try {
      const res = await fetch(`/api/offers/${offer.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ disabledByUser: !offer.disabledByUser }),
      });

      if (!res.ok) {
        const data = await res.json();
        toast.error(data.error || "Failed to update offer");
        return;
      }

      setOffers((prev) =>
        prev.map((o) =>
          o.id === offer.id ? { ...o, disabledByUser: !o.disabledByUser } : o
        )
      );
      toast.success(
        offer.disabledByUser ? "Offer re-enabled" : "Offer disabled"
      );
    } catch {
      toast.error("Something went wrong");
    } finally {
      setTogglingId(null);
    }
  }

  const filteredOffers =
    filter === "ALL" ? offers : offers.filter((o) => o.status === filter);

  function getTabCount(key: FilterTab): number {
    if (key === "ALL") return offers.length;
    return offers.filter((o) => o.status === key).length;
  }

  return (
    <div className="space-y-8">
      {/* ── Page header ── */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-gray-900">
            Offers
          </h1>
          <p className="mt-1 text-sm text-gray-500">
            Track and manage discount offers generated by your pricing rules.
          </p>
        </div>

        {/* Total count stat */}
        <div className="flex items-center gap-2 rounded-xl bg-indigo-50 px-4 py-2.5 ring-1 ring-inset ring-indigo-600/10">
          <svg
            className="h-4.5 w-4.5 text-indigo-600"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z"
            />
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M6 6h.008v.008H6V6Z"
            />
          </svg>
          <span className="text-sm font-semibold text-indigo-700">
            {offers.length}
          </span>
          <span className="text-sm text-indigo-600">
            {offers.length === 1 ? "offer" : "offers"} total
          </span>
        </div>
      </div>

      {/* ── Filter tabs (segmented control) ── */}
      <div className="inline-flex items-center gap-1 rounded-full bg-gray-100 p-1">
        {FILTER_TABS.map((tab) => {
          const count = getTabCount(tab.key);
          const isActive = filter === tab.key;

          return (
            <button
              key={tab.key}
              type="button"
              onClick={() => setFilter(tab.key)}
              className={`inline-flex items-center gap-1.5 rounded-full px-4 py-2 text-sm font-medium transition-all duration-200 ${
                isActive
                  ? "bg-white text-gray-900 shadow-sm ring-1 ring-gray-200"
                  : "text-gray-500 hover:text-gray-700"
              }`}
            >
              {tab.label}
              <span
                className={`inline-flex min-w-[20px] items-center justify-center rounded-full px-1.5 py-0.5 text-xs font-semibold leading-none ${
                  isActive
                    ? "bg-indigo-100 text-indigo-700"
                    : "bg-gray-200/80 text-gray-500"
                }`}
              >
                {count}
              </span>
            </button>
          );
        })}
      </div>

      {/* ── Offers table ── */}
      {loading ? (
        <div className="flex items-center justify-center py-16">
          <svg
            className="h-6 w-6 animate-spin text-indigo-600"
            fill="none"
            viewBox="0 0 24 24"
          >
            <circle
              className="opacity-25"
              cx="12"
              cy="12"
              r="10"
              stroke="currentColor"
              strokeWidth="4"
            />
            <path
              className="opacity-75"
              fill="currentColor"
              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
            />
          </svg>
          <span className="ml-3 text-sm font-medium text-gray-500">
            Loading offers...
          </span>
        </div>
      ) : filteredOffers.length === 0 ? (
        <div className="table-container">
          <div className="flex flex-col items-center justify-center py-20">
            {/* Tag icon */}
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gray-100">
              <svg
                className="h-7 w-7 text-gray-400"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z"
                />
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M6 6h.008v.008H6V6Z"
                />
              </svg>
            </div>
            <p className="mt-4 text-sm font-medium text-gray-900">
              No offers found
            </p>
            <p className="mt-1 text-sm text-gray-500">
              {filter === "ALL"
                ? "Offers will appear here once your pricing rules generate them."
                : `No offers with status "${filter.toLowerCase()}" right now.`}
            </p>
          </div>
        </div>
      ) : (
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Slot Time</th>
                <th>Service</th>
                <th>Rule</th>
                <th>Discount</th>
                <th>Price</th>
                <th>Status</th>
                <th>Enabled</th>
              </tr>
            </thead>
            <tbody>
              {filteredOffers.map((offer) => {
                const badge = STATUS_BADGE_MAP[offer.status];
                const isToggling = togglingId === offer.id;

                return (
                  <tr
                    key={offer.id}
                    className={
                      offer.disabledByUser ? "opacity-60" : undefined
                    }
                  >
                    {/* Slot time */}
                    <td className="whitespace-nowrap">
                      <div className="flex flex-col">
                        <span className="font-medium text-gray-900">
                          {format(
                            new Date(offer.slot.startTime),
                            "MMM d, yyyy"
                          )}
                        </span>
                        <span className="text-xs text-gray-500">
                          {format(new Date(offer.slot.startTime), "h:mm a")}
                        </span>
                      </div>
                    </td>

                    {/* Service type */}
                    <td className="text-gray-700">
                      {offer.slot.serviceType}
                    </td>

                    {/* Rule name */}
                    <td>
                      <span className="inline-flex items-center rounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">
                        {offer.rule.name}
                      </span>
                    </td>

                    {/* Discount percentage badge */}
                    <td>
                      <Badge variant="info">
                        {offer.discountPercent}% off
                      </Badge>
                    </td>

                    {/* Price: original struck through + discounted in green */}
                    <td>
                      <div className="flex items-center gap-2">
                        <span className="text-sm text-gray-400 line-through">
                          {formatPrice(offer.slot.basePriceCents)}
                        </span>
                        <span className="text-sm font-semibold text-emerald-600">
                          {formatPrice(offer.discountedPriceCents)}
                        </span>
                      </div>
                    </td>

                    {/* Status badge */}
                    <td>
                      <Badge variant={badge.variant}>{badge.label}</Badge>
                    </td>

                    {/* Toggle switch */}
                    <td>
                      <button
                        type="button"
                        role="switch"
                        aria-checked={!offer.disabledByUser}
                        disabled={isToggling}
                        onClick={() => toggleDisabled(offer)}
                        className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 disabled:cursor-wait disabled:opacity-50 ${
                          !offer.disabledByUser
                            ? "bg-indigo-600"
                            : "bg-gray-200"
                        }`}
                      >
                        <span className="sr-only">
                          {offer.disabledByUser
                            ? "Enable offer"
                            : "Disable offer"}
                        </span>
                        <span
                          aria-hidden="true"
                          className={`pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${
                            !offer.disabledByUser
                              ? "translate-x-5"
                              : "translate-x-0"
                          }`}
                        />
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
